name: Push Notification CI CD Pipeline

on:
  push:
    branches:
      - feat/add-push-notification-service
  pull_request:
    branches:
      - feat/add-push-notification-service

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: "notification-system/services/push-notification-service"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: "notification-system/services/push-notification-service"
        run: pytest

  deploy:
    needs: tests
    if: github.ref == 'refs/heads/feat/add-push-notification-service' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_SSH_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          port: ${{ secrets.AWS_SSH_PORT }}
          script: |
            set -e
            if [ ! -d "/home/ubuntu/notification-system/" ]; then
              git clone https://github.com/johnafariogun/notification-system
              cd notification-system
            fi
            cd ${{ secrets.AWS_DEPLOY_PATH }}
            git checkout ${{ secrets.AWS_DEPLOY_BRANCH }}
            git pull origin ${{ secrets.AWS_DEPLOY_BRANCH }}
            sudo docker compose up -d --build
